#version: '2'
version: '3.3'

services:
    # ------------------------------------------------------------------------------------
    # CREATE_CERTS
    # ------------------------------------------------------------------------------------
    #create_certs:
    #    container_name: elk_certs
    #    build: certs/
    #    volumes:
    #        - ./certs:/usr/share/elasticsearch/config/certificates
    # ------------------------------------------------------------------------------------
    # ELASTICSEARCH
    # ------------------------------------------------------------------------------------
    elasticsearch:
        container_name: elk_elasticsearch
        build: elasticsearch/
        restart: always
        volumes:
            - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
            - ./_data/elasticsearch:/usr/share/elasticsearch/data
              #- ./certs:/usr/share/elasticsearch/config/certificates
        ports:
            - "9200:9200"
            - "9300:9300"
        environment:
            ES_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - elk
              #depends_on: 
              #- create_certs

    # ------------------------------------------------------------------------------------
    # LOGSTASH
    # ------------------------------------------------------------------------------------
    logstash:
        container_name: elk_logstash
        build: logstash/
        restart: always
        volumes:
            - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
            - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
            - ./logstash/load:/usr/share/logstash/load:ro
        ports:
            - "5000:5000"
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - elk
        depends_on:
            - elasticsearch

    # ------------------------------------------------------------------------------------
    # KIBANA
    # ------------------------------------------------------------------------------------
    kibana:
        container_name: elk_kibana
        build: kibana/
        restart: always
        volumes:
            - ./kibana/config/:/usr/share/kibana/config:ro
        ports:
            - "5601:5601"
        networks:
            - elk
        depends_on:
            - elasticsearch

    # ------------------------------------------------------------------------------------
    # INGESTOR
    # ------------------------------------------------------------------------------------
    ingestor:
        container_name: elk_ingestor
        build: extensions/ingestor/
        volumes:
            - ./_data/nmap:/data/
        networks: 
            - elk
        depends_on:
            - elasticsearch

networks:
    elk:
        driver: bridge
