# https://github.com/elastic/kibana-docker
#FROM docker.elastic.co/kibana/kibana-oss:7.1.1
FROM docker.elastic.co/kibana/kibana:7.16.3

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
